### ISSUE TITLE
use `voi::evppi()` instead of internal `evppi()`

### ISSUE THREAD

**Issue by n8thangreen** [n8thangreen/BCEA#139]
Written wrapper to do this but there are discrepancies between packages that we need to decide about:

1. `voi::evppi()` returns a simple array where as `BCEA::evppi()` returns more information in a list. The list is used by several `BCEA` plotting functions
2. The "sal" and "so" methods in `voi` only work for single parameter EVPPI
3. `plot = TRUE` and `residual = TRUE` arguments in `BCEA` plot triangular mesh for SPDE-INLA and output fitted values for SPDE-INLA method. Do we want to retain this functionality?  They don't do anything for the other methods.

**Comment by n8thangreen** [comment]
@giabaio ❓

**Comment by giabaio** [comment]
I guess if we're porting the `voi::` version, we should make it so that people don't get inconsistencies... I guess from your list of options:
1. Use the BCEA::evppi() list output,
   - How do we do this without replacing `BCEA::evppi` with a local copy of `voi::evppi`, though?
2. Use single parameter case only like `voi::`
   - I'm OK with this. The `sal` and `so` are only there for historical reasons --- they are widely superseded, now...
3. Remove the plot and residual arguments 
   - These two require a power-user who knows what to do with these things (and INLA). Anna found it useful in debugging while we were creating the method and function, but probably we're OK to remove the mesh. As for the residuals, though, it'd be good to keep the functionality --- if the `voi::` output saves the INLA object (or parts of it), then it's OK and we may even write a specialised plot function (or write in a tutorial how to do it)...

**Comment by n8thangreen** [comment]
Thanks.

1. Some of the things are easy to get because theyre to do with the inputs and Im not sure about the others because theyre to do with intermediate things (which I think is what you mean)
- `index`: A numerical vector with the index associated with the parameters for which the EVPPI was calculated.
- `fitted.costs`: The fitted values for the costs.
- `fitted.effects`: The fitted values for the effects.
- parameters`: A single string containing the names of the parameters for which the EVPPI was calculated, used for plotting the EVPPI.
- `time`: Computational time (in seconds).
- `fit.c`: The object produced by the model fit for the costs.
- `fit.e`: The object produced by the model fit for the effects.
- `formula`: The formula used to fit the model.

3. Thats clearer. I'll keep `residuals` then

**Comment by giabaio** [comment]
I think for 1. some of these will be impossible to retrieve if they're not also stored in the `voi` object... It may be that we push a PR to `voi` to see if these can be added back to their function, for compatibility?

As for 3. if `residuals` is also in the `voi` output, then that would be easy, yes...

**Comment by n8thangreen** [comment]
closed by 5c8fc7d33c06980fa64a58e67bf40751faf2b157
(or before but some minor cleaning afterwards)
